import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
    }
});

export const sendOTPEmail = async (email, otp) => {
    const mailOptions = {
        from: `"SeatPro X Security" <${process.env.SMTP_USER}>`,
        to: email,
        subject: `Your OTP for SeatPro X`,
        text: `Your One-Time Password (OTP) for authentication is: ${otp}. This code expires in 10 minutes.`,
        html: `
            <div style="font-family: 'Outfit', 'Inter', sans-serif; color: #fff; background-color: #000; padding: 40px; border-radius: 20px; border: 1px solid #333; max-width: 500px; margin: 0 auto;">
                <h2 style="color: #00ff9d; margin-bottom: 20px; text-align: center; letter-spacing: -1px;">SeatPro X Security</h2>
                <p style="font-size: 1.1rem; line-height: 1.6; opacity: 0.9;">Greetings,</p>
                <p style="font-size: 1.1rem; line-height: 1.6; opacity: 0.9;">Your One-Time Password (OTP) for verification is below:</p>
                <div style="background: rgba(0, 255, 157, 0.1); border: 1px solid #00ff9d; padding: 20px; margin: 30px 0; text-align: center; border-radius: 12px;">
                    <span style="font-size: 3rem; font-weight: 900; color: #00ff9d; letter-spacing: 12px; margin-left: 12px;">${otp}</span>
                </div>
                <p style="font-size: 0.9rem; color: #94a3b8; text-align: center;">This code is valid for <strong>10 minutes</strong>. If you did not request this, please ignore this email.</p>
                <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #222; text-align: center;">
                    <p style="font-size: 0.8rem; color: #64748b;">Explicitly generated by the Security Engine</p>
                </div>
            </div>
        `
    };

    await transporter.sendMail(mailOptions);
};
